add_newline = false
format = "$directory$git_branch$git_status$character"

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[git_branch]
symbol = "ï˜ "
style = "bold"
format = "[$symbol$branch]($style)"

# If clean, this section is hidden.
[git_status]
style = "bold yellow"
format = ' [$all_status$ahead_behind]($style)'
modified = "*"
staged = "+"
deleted = "x"
untracked = "?"
