add_newline = false
format = "$directory$git_branch$git_status$character"

[directory]
disabled = false
truncation_length = 3   # specific folder count before shortening (e.g. .../a/b/c)
style = "bold blue"     # Blue color to separate it from Git
format = "[$path]($style) "

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[git_branch]
symbol = " "
style = "bold"
format = "[$symbol$branch]($style)"

# If clean, this section is hidden.
[git_status]
style = "bold yellow"
format = ' [$all_status$ahead_behind]($style)'
modified = "*"
staged = "+"
deleted = "x"
untracked = "?"
stashed = "" # "≡"
ahead = "⇡"
behind = "⇣"
